### ISSUE TITLE
add contributors

### ISSUE THREAD

**Issue by Vedant-Mhatre** [R-A-N-N/KBC-Game#11]
@all-contributors please add @nikita24383 for code

**Comment by Vedant-Mhatre** [comment]
@all-contributors please add @nikita24383 for code

**Comment by Vedant-Mhatre** [comment]
@all-contributors please add @nikita24383 for code

**Comment by Vedant-Mhatre** [comment]
@all-contributors please add @AmrutaKoshe for code

**Comment by Vedant-Mhatre** [comment]
@all-contributors please add @nikita24383 for code

**Comment by Vedant-Mhatre** [comment]
@all-contributors please add @nikita24383 for code

**Comment by Vedant-Mhatre** [comment]
@all-contributors please add @nikita24383 for code

**Comment by Vedant-Mhatre** [comment]
@all-contributors please add @nikita24383 for code

**Comment by Vedant-Mhatre** [comment]
@all-contributors please add @AmrutaKoshe for code

**Comment by Vedant-Mhatre** [comment]
@all-contributors please add @AmrutaKoshe for code

**Comment by nikita24383** [comment]
@all-contributors please add @RakshitaTantry28 for code

**Comment by nikita24383** [comment]
@all-contributors please add @nidhivanjare for code
