### ISSUE TITLE
Add contributors

### ISSUE THREAD

**Issue by nikita24383** [R-A-N-N/KBC-Game#5]
@all-contributors please add @nikita24383 for projectManagement

**Comment by nikita24383** [comment]
@all-contributors please add @AmrutaKoshe for code

**Comment by nikita24383** [comment]
@all-contributors please add @nikita24383 for projectManagement

**Comment by nikita24383** [comment]
@all-contributors please add @RakshitaTantry28  for bug

**Comment by nikita24383** [comment]
@all-contributors please add @nidhivanjare  for design

**Comment by AmrutaKoshe** [comment]
@all-contributors please add @nikita24383 for talk
